# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.12.5/www/docs/static/schema.json

version: 2

dist: dist/goreleaser

builds:
  - id: manager
    main: cmd/main.go
    binary: manager
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s"
      - "-w"
      - "-X github.com/idebeijer/gameserver-operator/pkg/version.version={{ .Version }}"
      - "-X github.com/idebeijer/gameserver-operator/pkg/version.commit={{ .ShortCommit }}"
      - "-X github.com/idebeijer/gameserver-operator/pkg/version.date={{ .Date }}"
      - "-X github.com/idebeijer/gameserver-operator/pkg/version.builtBy=goreleaser"

dockers_v2:
  - dockerfile: Dockerfile.goreleaser
    ids:
      - manager
    images:
      - "ghcr.io/idebeijer/gameserver-operator"
      - "docker.io/idebeijer/gameserver-operator"
    tags:
      - "{{ .Version }}"
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.authors": "Igor de Beijer"
      "org.opencontainers.image.url": "https://github.com/idebeijer/gameserver-operator"
      "org.opencontainers.image.documentation": "https://github.com/idebeijer/gameserver-operator/blob/main/README.md"
      "org.opencontainers.image.source": "{{ .GitURL }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.vendor": "idebeijer"
      "org.opencontainers.image.licenses": "MIT"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Kubernetes operator for managing game servers"
    platforms:
      - linux/amd64
      - linux/arm64

snapshot:
  version_template: "{{ incpatch .Version }}"

release:
  footer: |
    **Full Changelog**: https://github.com/idebeijer/gameserver-operator/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  sort: asc
  use: github
  groups:
    - title: "Breaking changes"
      regexp: '^.*?\w+(\(.+\))?!:\s?.+$'
      order: 0
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 2
    - title: "Documentation"
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 3
    - title: "Build system"
      regexp: '^.*?(build|ci)(\(.+\))??!?:.+$'
      order: 4
    - title: "Others"
      order: 999
  filters:
    exclude:
      - '^.*?(test|style)(\(.+\))??!?:.+$'
      - 'initial commit'
