FROM gcr.io/distroless/static:nonroot@sha256:e8a4044e0b4ae4257efa45fc026c0bc30ad320d43bd4c1a7d5271bd241e386d0 AS runtime
ARG TARGETPLATFORM

COPY --chown=65532:65532 ${TARGETPLATFORM}/manager /usr/local/bin/manager
WORKDIR /home/nonroot
USER 65532:65532

ENTRYPOINT ["/usr/local/bin/manager"]
