FROM gcr.io/distroless/static:nonroot@sha256:01e550fdb7ab79ee7be5ff440a563a58f1fd000ad9e0c532e65c3d23f917f1c5 AS runtime
ARG TARGETPLATFORM

WORKDIR /
COPY --chown=65532:65532 ${TARGETPLATFORM}/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]
