FROM gcr.io/distroless/static:nonroot@sha256:0376b514983f02c630de9ed8abadd33968ddb778f9f383412a12babe639cbaaa AS runtime
ARG TARGETPLATFORM

WORKDIR /
COPY --chown=65532:65532 ${TARGETPLATFORM}/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]
