---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - games.idebeijer.github.io
  resources:
  - gameservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - games.idebeijer.github.io
  resources:
  - gameservers/finalizers
  verbs:
  - update
- apiGroups:
  - games.idebeijer.github.io
  resources:
  - gameservers/status
  verbs:
  - get
  - patch
  - update
