apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
spec:
  selector:
    app.kubernetes.io/instance: gameserver-sample
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565