name: Test Report

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@fe45e9537387dac839af0d33ba56eed8e24189e8 # v2
        with:
          artifact: test-results
          name: Unit Tests
          path: "*.xml"
          reporter: java-junit
